version: '2.4'
services:
  easy2monitor.planblick.svc:
    build: .
    image: easy2monitor
    restart: always
    mem_limit: 400m
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      FRONTEND_PORT: ${FRONTEND_PORT}
      FLASK_DEBUG: ${FLASK_DEBUG}
      DB_DRIVER:  ${DB_DRIVER}
      DB_NAME:  ${DB_NAME}
      DB_DEBUG:  ${DB_DEBUG}
      MQ_HOST: ${MQ_HOST}
      MQ_USERNAME: ${MQ_USERNAME}
      MQ_PASSWORD: ${MQ_PASSWORD}
      MQ_PORT: ${MQ_PORT}
      MQ_VHOST: ${MQ_VHOST}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_LOGIN: ${SMTP_LOGIN}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      MAIL_SENDER: ${MAIL_SENDER}
      MAIL_RECIPIENT: ${MAIL_RECIPIENT}
      SEND_MAIL: ${SEND_MAIL}
      SEND_SMS: ${SEND_SMS}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      SMS_RECIPIENTS: ${SMS_RECIPIENTS}
    stdin_open: true
    tty: true
    ports:
    - "8000:8000"
    volumes:
    - ./src:/src

  rabbitmq.planblick.svc:
    image: "rabbitmq:3.6-management"
    ports:
      - 5672:5672
      - 15672:15672
